name: sliverbar_with_card
description: A Flutter package to create a SliverAppBar with a Card with action button and back button, excellent to show catalog items.
author: Rodrigo Dias <rod90ad@gmail.com>
homepage: https://github.com/rod90ad/sliverbar_with_card
version: 0.1.4

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:

flutter: